# Default OpenNMT parameters.
model_dir: /home/at15/workspace/src/github.com/at15/snowbot-model/tf_opennmt_cornell

# python -m bin.build_vocab --size 50000 --save_vocab /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/src-vocab.txt /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/src-train.txt
# python -m bin.build_vocab --size 50000 --save_vocab /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/tgt-vocab.txt /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/tgt-train.txt
# python -m bin.main train --model config/models/nmt_small.py --config /home/at15/workspace/src/github.com/at15/snowbot/config/tf_opennmt_cornell.yml

data:
  train_features_file: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/src-train.txt
  train_labels_file: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/tgt-train.txt
  eval_features_file: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/src-val.txt
  eval_labels_file: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/tgt-val.txt
  source_words_vocabulary: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/src-vocab.txt
  target_words_vocabulary: /home/at15/workspace/src/github.com/at15/snowbot-data/cornell/tgt-vocab.txt

params:
  optimizer: GradientDescentOptimizer
  learning_rate: 1.0
  param_init: 0.1
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 100000
  start_decay_steps: 500000
  beam_width: 5
  maximum_iterations: 250

train:
  batch_size: 64
  save_checkpoints_steps: 5000
  save_summary_steps: 50
  train_steps: 10000 # 1000000
  eval_delay: 18000 # Every 5 hours.
  maximum_features_length: 50
  maximum_labels_length: 50

infer:
  batch_size: 30
